os: linux
dist: trusty
sudo: false
language: python
python:
  - "3.6"
  - "nightly"
  - "pypy3"
cache:
  pip: true  # caches $HOME/.cache/pip

branches:
  only:
  - master

env:
matrix:
  allow_failures:
  - python: "pypy3"

install:
  - pip install -r requirements.txt

script:
  - pytest -v
